name: RSS Auto Publish

on:
  push:
    branches:
      - main       # Run on push to main branch
  schedule:
    - cron: "0 */3 * * *"   # Run every 3 hours UTC
  workflow_dispatch:         # Manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script with secrets
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          WP_SITE_URL: ${{ secrets.WP_SITE_URL }}
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          DEFAULT_IMAGE_URL: ${{ secrets.DEFAULT_IMAGE_URL }}
        run: python main.py
